name: Run
on:
  workflow_dispatch:
jobs:
  run-script:
    name: Zwift to Garmin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run main.py
      run: python main.py
      env:
        ZWIFT_USERNAME: ${{ secrets.ZWIFT_USERNAME }}
        ZWIFT_PASSWORD: ${{ secrets.ZWIFT_PASSWORD }}
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}